FROM python:3.12-slim

WORKDIR /code

COPY monitoring/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY monitoring/ ./monitoring/

EXPOSE 8501

CMD ["streamlit", "run", "monitoring/dashboard.py", "--server.address=0.0.0.0"]
